// Client-side reads of the public register. No backend: the app fetches
// content/index.json (regenerated by CI on every merge — see
// .github/workflows/build-index.yml) for the list/map view, and falls back
// to reading a single mosque's raw markdown when the app wants the freshest
// possible copy of one record (e.g. right after a moderator approves an
// edit and before the next index rebuild lands).

import type { Mosque } from './types';

export interface RegisterConfig {
  /** e.g. "your-org/mihrab-register" */
  githubRepo: string;
  /** branch or tag to read from */
  ref?: string;
}

function rawBase(cfg: RegisterConfig) {
  return `https://raw.githubusercontent.com/${cfg.githubRepo}/${cfg.ref ?? 'main'}`;
}

export async function fetchRegisterIndex(cfg: RegisterConfig): Promise<Mosque[]> {
  const res = await fetch(`${rawBase(cfg)}/content/index.json`, {
    // index.json is small and changes rarely; let normal HTTP caching apply.
    cache: 'default',
  });
  if (!res.ok) throw new Error(`Failed to fetch register index: ${res.status}`);
  const json = await res.json();
  return json.mosques as Mosque[];
}

/** Parses the same flat frontmatter shape as content/scripts/build-index.mjs. */
function parseScalar(raw: string): unknown {
  const v = raw.trim();
  if (v === 'true') return true;
  if (v === 'false') return false;
  if (/^-?\d+(\.\d+)?$/.test(v)) return Number(v);
  return v.replace(/^"(.*)"$/, '$1');
}

function parseInline(raw: string): unknown {
  const v = raw.trim();
  if (v.startsWith('[') && v.endsWith(']')) {
    const inner = v.slice(1, -1).trim();
    return inner ? inner.split(',').map((s) => parseScalar(s)) : [];
  }
  if (v.startsWith('{') && v.endsWith('}')) {
    const inner = v.slice(1, -1).trim();
    const obj: Record<string, unknown> = {};
    inner.split(',').forEach((pair) => {
      const [k, ...rest] = pair.split(':');
      obj[k.trim()] = parseScalar(rest.join(':'));
    });
    return obj;
  }
  return parseScalar(v);
}

export function parseMosqueMarkdown(slug: string, raw: string): Mosque {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw);
  if (!match) throw new Error(`No frontmatter in ${slug}.md`);
  const [, fmText, body] = match;
  const lines = fmText.split(/\r?\n/);
  const data: Record<string, unknown> = {};
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }
    const top = /^([a-zA-Z0-9_]+):\s*(.*)$/.exec(line);
    if (!top) { i++; continue; }
    const [, key, rest] = top;
    if (rest.trim() !== '') {
      data[key] = parseInline(rest);
      i++;
    } else {
      const nested: Record<string, unknown> = {};
      i++;
      while (i < lines.length && /^\s+\S/.test(lines[i])) {
        const nm = /^\s+([a-zA-Z0-9_]+):\s*(.*)$/.exec(lines[i]);
        if (nm) nested[nm[1]] = parseInline(nm[2]);
        i++;
      }
      data[key] = nested;
    }
  }
  const [notes] = body.trim().split('\n_—');
  const notesByMatch = /_—\s*(.+)_/.exec(body);
  return {
    ...(data as object),
    slug,
    notes: notes.trim(),
    notesBy: notesByMatch ? notesByMatch[1] : '',
  } as Mosque;
}

export async function fetchMosqueMarkdown(cfg: RegisterConfig, slug: string): Promise<Mosque> {
  const res = await fetch(`${rawBase(cfg)}/content/register/${slug}.md`, { cache: 'no-store' });
  if (!res.ok) throw new Error(`Failed to fetch ${slug}.md: ${res.status}`);
  const raw = await res.text();
  return parseMosqueMarkdown(slug, raw);
}
